<?php
$z[0]=Array("item","",4,88);
$z[0][4]['name']="网站建设";
$z[0][4]['link']="http://www.panqan.com/";
$z[0][4]['rank']="";
$z[0][4]['target']="_blank";
$z[1]=Array("item","",92,179);
$z[1][4]['name']="智能硬件";
$z[1][4]['link']="http://www.haopantou.com/";
$z[1][4]['rank']="";
$z[1][4]['target']="_blank";
$z[2]=Array("item","",185,283);
$z[2][4]['name']="微型投影仪";
$z[2][4]['link']="https://shop115667921.taobao.com/";
$z[2][4]['rank']="";
$z[2][4]['target']="_blank";

?>