<?php
$z[0]=Array("type","<a  class=\"footicon fa\"target=\"_blank\" href=\"[field:typeurl/]\" >[field:typename/]</a>",72,191);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<a  class=\"footicon fb\"target=\"_blank\" href=\"[field:typeurl/]\" >[field:typename/]</a>",208,328);
$z[1][4]['typeid']="14";
$z[2]=Array("type","<a  class=\"footicon fc\"target=\"_blank\" href=\"[field:typeurl/]\" >[field:typename/]</a>",345,465);
$z[2][4]['typeid']="16";
$z[3]=Array("global","",560,591);
$z[3][4]['name']="cfg_company_name";
$z[4]=Array("global","",652,684);
$z[4][4]['name']="cfg_company_phone";
$z[5]=Array("global","",716,750);
$z[5][4]['name']="cfg_company_address";
$z[6]=Array("global","",758,790);
$z[6][4]['name']="cfg_company_email";
$z[7]=Array("global","",2683,2712);
$z[7][4]['name']="cfg_company_qq";
$z[8]=Array("global","",2797,2826);
$z[8][4]['name']="cfg_company_qq";

?>