<?php
$z[0]=Array("global","",204,231);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",252,279);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",352,379);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",384,415);
$z[3][4]['name']="cfg_company_name";
$z[4]=Array("global","",501,533);
$z[4][4]['name']="cfg_company_email";
$z[5]=Array("global","",569,600);
$z[5][4]['name']="cfg_company_name";
$z[6]=Array("channelartlist","\r\n  <li><a class=\"nn n{dede:global name=itemindex runphp='yes'}@me=@me+1;{/dede:global}\" href=\"#\">{dede:global name=itemindex runphp='yes'}@me=@me-1;{/dede:global}</a>\r\n    <div> {dede:channel type='son' noself='yes'}<a href=\"[field:typelink/]\" class=\"on\" >[field:typename/]</a>{/dede:channel} </div>\r\n  </li>\r\n  ",1002,1379);
$z[6][4]['typeid']="top";
$z[6][4]['row']="6";

?>