<?php
$z[0]=Array("global","",204,231);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",252,279);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",352,379);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",384,415);
$z[3][4]['name']="cfg_company_name";
$z[4]=Array("global","",501,533);
$z[4][4]['name']="cfg_company_email";
$z[5]=Array("global","",569,600);
$z[5][4]['name']="cfg_company_name";
$z[6]=Array("channelartlist","\r\n      <li class=\"mainlevel\" id=\"mainlevel_0[field:global.autoindex/]\">\r\n        <a href=\"{dede:field name='typeurl'/}\"  title=\"{dede:field name='typename'/}\" class=\"navList\">{dede:field name='typename'/}</a>\r\n        <ul id=\"sub_01\" class=\"menual\">\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n      </li>\r\n      ",1410,1898);
$z[6][4]['typeid']="top";

?>