<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",631,666);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n    <li class=''> <a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n    ",963,1178);
$z[5][4]['type']="son";
$z[5][4]['row']="25";
$z[5][4]['currentstyle']="<li class='hover'> <a href='~typelink~'>~typename~</a></li>";
$z[6]=Array("field","",1349,1378);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n      <li style=\"display: list-item;\"><span>[[field:pubdate   function=mydate('Y-m-d',@me)/]]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n      ",1501,1697);
$z[7][4]['pagesize']="12";
$z[8]=Array("pagelist","",1818,1889);
$z[8][4]['istitem']="index,pre,next,end,option,info,";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2021,2058);
$z[9][4]['filename']="footer.htm";

?>